name: PR build check
on:
  #  push:
  #    branches:
  #      - develop
  #    paths-ignore:
  #      - '**.md'
  pull_request:
    paths:
      - '**'
      - '!**.md'
      - '!i18n-kmk/src/commonMain/moko-resources/**/strings.xml'
      - '!i18n-kmk/src/commonMain/moko-resources/**/plurals.xml'
      - 'i18n-kmk/src/commonMain/moko-resources/base/strings.xml'
      - 'i18n-kmk/src/commonMain/moko-resources/base/plurals.xml'
  # Dispatch or Manual triggers
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: Build app
    runs-on: 'ubuntu-24.04'

    steps:
      - name: Clone repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Dependency Review
        uses: actions/dependency-review-action@40c09b7dc99638e5ddb0bfd91c1673effc064d8a # v4.8.1

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0

      - name: Set up JDK
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          java-version: 17
          distribution: temurin

      - name: Set up gradle
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5

      - name: Decode Keystore
        if: github.repository == github.event.pull_request.head.repo.full_name
        run: echo "${{ secrets.SIGNING_KEY }}" | base64 -d > app/keystore.jks

      - name: Check code format
        run: ./gradlew spotlessCheck

      - name: Build signed app
        if: github.repository == github.event.pull_request.head.repo.full_name
        run: ./gradlew assembleFoss
        env:
          KEYSTORE_FILE: keystore.jks
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          ALIAS: ${{ secrets.ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Build unsigned app
        if: github.repository != github.event.pull_request.head.repo.full_name
        run: ./gradlew assembleFoss

      - name: Run unit tests
        run: ./gradlew testReleaseUnitTest

      - name: Signed File name
        id: signed_filename
        if: github.repository == github.event.pull_request.head.repo.full_name
        run: |
          echo "APK_NAME=app-universal-foss.apk" >> $GITHUB_OUTPUT

      - name: Unsigned File name
        id: unsigned_filename
        if: github.repository != github.event.pull_request.head.repo.full_name
        run: |
          echo "APK_NAME=app-universal-foss.apk" >> $GITHUB_OUTPUT

      - name: Rename apk
        id: current_commit
        run: |
          set -e
          echo "The git ref is: ${{ github.ref }}"
          version_tag=p$(echo ${{ github.ref }} | cut -d '/' -f 3)
          commit_count=$(git rev-list --count HEAD)
          echo "VERSION_TAG=$version_tag"
          echo "VERSION_TAG=$version_tag" >> $GITHUB_OUTPUT
          echo "COMMIT_COUNT=$commit_count"
          echo "COMMIT_COUNT=$commit_count" >> $GITHUB_OUTPUT
          mv app/build/outputs/apk/foss/${{ steps.signed_filename.outputs.APK_NAME }}${{ steps.unsigned_filename.outputs.APK_NAME }} Komikku-foss-$version_tag-r$commit_count.apk

      - name: Upload APK
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: Komikku-foss-${{ steps.current_commit.outputs.VERSION_TAG }}-r${{ steps.current_commit.outputs.COMMIT_COUNT }}.apk
          path: ./*.apk

      - name: Upload mapping
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: mapping-${{ github.sha }}
          path: app/build/outputs/mapping/foss
